name: my_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.1
  geolocator: ^10.1.0
  flutter_polyline_points: 2.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  jwt_decode: ^0.3.1
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.1
  stomp_dart_client: ^0.4.4
  web_socket_channel: ^2.4.0
  intl: ^0.18.1
  location: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/schoolbus.png
    - assets/images/schoolbus1.png
    - assets/images/logo.jpg
    - assets/images/bus_logo.jpg
    - assets/images/bus_icon.png

